# Generated by Django 3.1.7 on 2021-05-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_matricula', models.IntegerField()),
                ('aluno_nome', models.CharField(max_length=50)),
                ('aluno_email', models.EmailField(max_length=254)),
                ('aluno_nota', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
