# Generated by Django 3.1.7 on 2021-05-04 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='aluno_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='aluno_matricula',
            new_name='matricula',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='aluno_nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='aluno_nota',
            new_name='nota',
        ),
    ]
