# Generated by Django 3.1.7 on 2021-05-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_auto_20210515_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
