# Generated by Django 3.2.5 on 2021-07-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
