# Generated by Django 3.2.5 on 2021-07-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_auto_20210718_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('alunos', models.ManyToManyField(to='aluno.Aluno')),
            ],
        ),
    ]
